name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'infra/**'
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/infrastructure.yml'

  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - 'infra/**'
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/infrastructure.yml'

env:
  GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  REGISTRY: asia-south1-docker.pkg.dev
  IMAGE_NAME: kavach-backend
  ARTIFACT_REPO_NAME: kavach-artifact-repo-dev
  REGION: asia-south1

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    name: 'Build and Push Image'
    runs-on: ubuntu-latest
    environment: kavach-gcp-dev
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GOOGLE_CLOUD_PROJECT }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Generate Tag
        id: tag
        run: |
          # Generate a 7-character tag from commit SHA
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "tag=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "Generated tag: $SHORT_SHA"

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.GOOGLE_CLOUD_PROJECT }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} .
          docker push ${{ env.REGISTRY }}/${{ env.GOOGLE_CLOUD_PROJECT }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}

      - name: Build and Push Latest Tag
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.GOOGLE_CLOUD_PROJECT }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ env.REGISTRY }}/${{ env.GOOGLE_CLOUD_PROJECT }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.GOOGLE_CLOUD_PROJECT }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Build Summary
        run: |
          echo "## 🐳 Docker Image Built Successfully"
          echo ""
          echo "**Image:** ${{ env.REGISTRY }}/${{ env.GOOGLE_CLOUD_PROJECT }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}"
          echo "**Tag:** ${{ steps.tag.outputs.tag }}"
          echo "**Commit:** ${{ github.sha }}"
          echo "**Branch:** ${{ github.ref_name }}"
          echo "**Region:** ${{ env.REGION }}"
          echo ""
          echo "### 🔗 Links:"
          echo "- [Artifact Registry](https://console.cloud.google.com/artifacts?project=${{ env.GOOGLE_CLOUD_PROJECT }})"
          echo "- [Cloud Run](https://console.cloud.google.com/run?project=${{ env.GOOGLE_CLOUD_PROJECT }})" 